+ source ../common/common_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Fri Aug 25 05:20:56 2023 - INFO  - Start environmental preparation.
+ cp /etc/dhcp/dhcpd.conf /etc/dhcp/dhcpd.bak
+ echo 'ddns-update-style none;
ignore client-updates;
subnet 192.168.0.0 netmask 255.255.255.0 {
range 192.168.0.200 192.168.0.230;
    option domain-name-servers 192.168.0.1;
    option domain-name "test.local";
    option routers 192.168.0.1;
    option subnet-mask 255.255.255.0;
    default-lease-time 43200;
    max-lease-time 86400;
}'
+ ip addr add 192.168.0.1 dev ''
Cannot find device ""
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Fri Aug 25 05:20:56 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Fri Aug 25 05:20:56 2023 - INFO  - Start testing...
+ test_execution dhcpd.service
+ service=dhcpd.service
++ date '+%Y-%m-%d %T'
+ log_time='2023-08-25 05:20:56'
+ test_restart dhcpd.service
+ service=dhcpd.service
+ systemctl restart dhcpd.service
Job for dhcpd.service failed because the control process exited with error code.
See "systemctl status dhcpd.service" and "journalctl -xeu dhcpd.service" for details.
+ CHECK_RESULT 1 0 0 'dhcpd.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='dhcpd.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'dhcpd.service restart failed'
+ LOG_ERROR 'dhcpd.service restart failed'
+ message='dhcpd.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'dhcpd.service restart failed'
Fri Aug 25 05:20:56 2023 - ERROR - dhcpd.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Fri Aug 25 05:20:56 2023 - ERROR - ../common/common_lib.sh line 34
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ grep 'Active: active'
+ systemctl status dhcpd.service
+ CHECK_RESULT 1 0 0 'dhcpd.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='dhcpd.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'dhcpd.service restart failed'
+ LOG_ERROR 'dhcpd.service restart failed'
+ message='dhcpd.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'dhcpd.service restart failed'
Fri Aug 25 05:21:01 2023 - ERROR - dhcpd.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Fri Aug 25 05:21:01 2023 - ERROR - ../common/common_lib.sh line 37
+ return 0
+ systemctl stop dhcpd.service
+ CHECK_RESULT 0 0 0 'dhcpd.service stop failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='dhcpd.service stop failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status dhcpd.service
+ grep 'Active: inactive'
+ CHECK_RESULT 1 0 0 'dhcpd.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='dhcpd.service stop failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'dhcpd.service stop failed'
+ LOG_ERROR 'dhcpd.service stop failed'
+ message='dhcpd.service stop failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'dhcpd.service stop failed'
Fri Aug 25 05:21:06 2023 - ERROR - dhcpd.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Fri Aug 25 05:21:06 2023 - ERROR - ../common/common_lib.sh line 42
+ return 0
+ systemctl start dhcpd.service
Job for dhcpd.service failed because the control process exited with error code.
See "systemctl status dhcpd.service" and "journalctl -xeu dhcpd.service" for details.
+ CHECK_RESULT 1 0 0 'dhcpd.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='dhcpd.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'dhcpd.service start failed'
+ LOG_ERROR 'dhcpd.service start failed'
+ message='dhcpd.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'dhcpd.service start failed'
Fri Aug 25 05:21:06 2023 - ERROR - dhcpd.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Fri Aug 25 05:21:06 2023 - ERROR - ../common/common_lib.sh line 44
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status dhcpd.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'dhcpd.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='dhcpd.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'dhcpd.service start failed'
+ LOG_ERROR 'dhcpd.service start failed'
+ message='dhcpd.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'dhcpd.service start failed'
Fri Aug 25 05:21:11 2023 - ERROR - dhcpd.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Fri Aug 25 05:21:11 2023 - ERROR - ../common/common_lib.sh line 47
+ return 0
+ test_enabled dhcpd.service
+ service=dhcpd.service
++ systemctl is-enabled dhcpd.service
+ state=disabled
+ '[' disabled == enabled ']'
+ '[' disabled == disabled ']'
++ systemctl enable dhcpd.service
++ grep 'Created symlink'
++ awk '{print $3}'
+ symlink_file=/etc/systemd/system/multi-user.target.wants/dhcpd.service
+ find /etc/systemd/system/multi-user.target.wants/dhcpd.service
/etc/systemd/system/multi-user.target.wants/dhcpd.service
+ CHECK_RESULT 0 0 0 'dhcpd.service enable failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='dhcpd.service enable failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl disable dhcpd.service
Removed "/etc/systemd/system/multi-user.target.wants/dhcpd.service".
+ find /etc/systemd/system/multi-user.target.wants/dhcpd.service
find: ‘/etc/systemd/system/multi-user.target.wants/dhcpd.service’: No such file or directory
+ CHECK_RESULT 1 0 1 'dhcpd.service disable failed'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='dhcpd.service disable failed'
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ journalctl --since '2023-08-25 05:20:56' -u dhcpd.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
Aug 25 05:20:56 10.0.2.15 systemd[1]: dhcpd.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 05:20:56 10.0.2.15 systemd[1]: dhcpd.service: Failed with result 'exit-code'.
Aug 25 05:20:56 10.0.2.15 systemd[1]: Failed to start DHCPv4 Server Daemon.
Aug 25 05:21:06 10.0.2.15 systemd[1]: dhcpd.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 05:21:06 10.0.2.15 systemd[1]: dhcpd.service: Failed with result 'exit-code'.
Aug 25 05:21:06 10.0.2.15 systemd[1]: Failed to start DHCPv4 Server Daemon.
+ CHECK_RESULT 0 0 1 'There is an error message for the log of dhcpd.service'
+ actual_result=0
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of dhcpd.service'
+ '[' -z 0 ']'
+ '[' 1 -eq 0 ']'
+ test 0x == 0x
+ test -n 'There is an error message for the log of dhcpd.service'
+ LOG_ERROR 'There is an error message for the log of dhcpd.service'
+ message='There is an error message for the log of dhcpd.service'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'There is an error message for the log of dhcpd.service'
Fri Aug 25 05:21:11 2023 - ERROR - There is an error message for the log of dhcpd.service
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 28'
+ message='../common/common_lib.sh line 28'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 28'
Fri Aug 25 05:21:11 2023 - ERROR - ../common/common_lib.sh line 28
+ return 0
+ test_reload dhcpd.service
+ service=dhcpd.service
+ systemctl start dhcpd.service
Job for dhcpd.service failed because the control process exited with error code.
See "systemctl status dhcpd.service" and "journalctl -xeu dhcpd.service" for details.
+ systemctl reload dhcpd.service
+ grep 'Job type reload is not applicable'
Failed to reload dhcpd.service: Job type reload is not applicable for unit dhcpd.service.
+ CHECK_RESULT 0 0 0 'Job type reload is not applicable for unit dhcpd.service'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Job type reload is not applicable for unit dhcpd.service'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl status dhcpd.service
+ grep 'Active: active'
+ systemctl status dhcpd.service
+ grep 'inactive (dead)'
+ return 1
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Fri Aug 25 05:21:11 2023 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 6
+ test 6 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Aug 25 05:21:11 2023 - ERROR - failed to execute the case.
+ exit 6
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Fri Aug 25 05:21:12 2023 - INFO  - start environment cleanup.
+ systemctl stop dhcpd.service
+ mv -f /etc/dhcp/dhcpd.bak /etc/dhcp/dhcpd.conf
+ ip addr del 192.168.0.1 dev ''
Warning: Executing wildcard deletion to stay compatible with old scripts.
         Explicitly specify the prefix length (192.168.0.1/32) to avoid this warning.
         This special behaviour is likely to disappear in further releases,
         fix your scripts!
Cannot find device ""
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Fri Aug 25 05:21:12 2023 - INFO  - Finish environment cleanup!
