+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Aug 18 12:29:50 2023 - INFO  - Start to run test.
+ SSH_SCP ../common/SAVE_RESROER.sh @:/tmp/SAVE_RESROER.sh
+ src=../common/SAVE_RESROER.sh
+ dest=@:/tmp/SAVE_RESROER.sh
+ remotepasswd='openEuler12#$'
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshscp.sh -p 'openEuler12#$' -o 22 -s ../common/SAVE_RESROER.sh -d @:/tmp/SAVE_RESROER.sh
Fri Aug 18 12:29:50 2023 - WARN  - the remote password uses the default configuration.
Fri Aug 18 12:29:50 2023 - WARN  - the connect port using the default configuration
spawn scp -P 22 -r ../common/SAVE_RESROER.sh @:/tmp/SAVE_RESROER.sh
ssh: Could not resolve hostname : Name or service not known
scp: Connection closed
+ ret=255
+ test 255 -ne 0
+ LOG_ERROR 'Failed in remote SCP operation: 255'
+ message='Failed in remote SCP operation: 255'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote SCP operation: 255'
Fri Aug 18 12:29:50 2023 - ERROR - Failed in remote SCP operation: 255
+ return 255
+ SSH_CMD 'bash -x /tmp/SAVE_RESROER.sh start'
+ cmd='bash -x /tmp/SAVE_RESROER.sh start'
+ remoteip=
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'bash -x /tmp/SAVE_RESROER.sh start' -i '' -u root -p 'openEuler12#$' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Fri Aug 18 12:29:50 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ SSH_SCP @:/etc/sysconfig/ipvsadm ./ipvsadm
+ src=@:/etc/sysconfig/ipvsadm
+ dest=./ipvsadm
+ remotepasswd='openEuler12#$'
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshscp.sh -p 'openEuler12#$' -o 22 -s @:/etc/sysconfig/ipvsadm -d ./ipvsadm
Fri Aug 18 12:29:50 2023 - WARN  - the remote password uses the default configuration.
Fri Aug 18 12:29:50 2023 - WARN  - the connect port using the default configuration
spawn scp -P 22 -r @:/etc/sysconfig/ipvsadm ./ipvsadm
ssh: Could not resolve hostname : Name or service not known
scp: Connection closed
+ ret=255
+ test 255 -ne 0
+ LOG_ERROR 'Failed in remote SCP operation: 255'
+ message='Failed in remote SCP operation: 255'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote SCP operation: 255'
Fri Aug 18 12:29:50 2023 - ERROR - Failed in remote SCP operation: 255
+ return 255
++ wc -l ./ipvsadm
++ grep -cE 2
wc: ./ipvsadm: No such file or directory
+ CHECK_RESULT 0 1
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ipvs_SAVE_01.sh line 26'
+ message='oe_test_ipvs_SAVE_01.sh line 26'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ipvs_SAVE_01.sh line 26'
Fri Aug 18 12:29:50 2023 - ERROR - oe_test_ipvs_SAVE_01.sh line 26
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ SSH_SCP @:/tmp/ipvsadm_restore.txt ./ipvsadm_restore.txt
+ src=@:/tmp/ipvsadm_restore.txt
+ dest=./ipvsadm_restore.txt
+ remotepasswd='openEuler12#$'
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshscp.sh -p 'openEuler12#$' -o 22 -s @:/tmp/ipvsadm_restore.txt -d ./ipvsadm_restore.txt
Fri Aug 18 12:29:55 2023 - WARN  - the remote password uses the default configuration.
Fri Aug 18 12:29:55 2023 - WARN  - the connect port using the default configuration
spawn scp -P 22 -r @:/tmp/ipvsadm_restore.txt ./ipvsadm_restore.txt
ssh: Could not resolve hostname : Name or service not known
scp: Connection closed
+ ret=255
+ test 255 -ne 0
+ LOG_ERROR 'Failed in remote SCP operation: 255'
+ message='Failed in remote SCP operation: 255'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote SCP operation: 255'
Fri Aug 18 12:29:55 2023 - ERROR - Failed in remote SCP operation: 255
+ return 255
++ grep -cE Route ./ipvsadm_restore.txt
grep: ./ipvsadm_restore.txt: No such file or directory
+ CHECK_RESULT '' 1
+ actual_result=
+ expect_result=1
+ mode=0
+ error_log=
+ '[' -z '' ']'
+ LOG_ERROR 'Missing actual error code.'
+ message='Missing actual error code.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Missing actual error code.'
Fri Aug 18 12:29:55 2023 - ERROR - Missing actual error code.
+ return 1
++ grep -cE rr ./ipvsadm_restore.txt
grep: ./ipvsadm_restore.txt: No such file or directory
+ CHECK_RESULT '' 1
+ actual_result=
+ expect_result=1
+ mode=0
+ error_log=
+ '[' -z '' ']'
+ LOG_ERROR 'Missing actual error code.'
+ message='Missing actual error code.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Missing actual error code.'
Fri Aug 18 12:29:55 2023 - ERROR - Missing actual error code.
+ return 1
+ SSH_CMD 'ipvsadm -C && systemctl reboot &'
+ cmd='ipvsadm -C && systemctl reboot &'
+ remoteip=
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'ipvsadm -C && systemctl reboot &' -i '' -u root -p 'openEuler12#$' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Fri Aug 18 12:29:55 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ SLEEP_WAIT 60
+ wait_time=60
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 60 --cmd '' --mode 1
+ SSH_CMD 'ipvsadm -R < /etc/sysconfig/ipvsadm && ipvsadm>>/tmp/ipvsadm_restore1.txt '
+ cmd='ipvsadm -R < /etc/sysconfig/ipvsadm && ipvsadm>>/tmp/ipvsadm_restore1.txt '
+ remoteip=
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'ipvsadm -R < /etc/sysconfig/ipvsadm && ipvsadm>>/tmp/ipvsadm_restore1.txt ' -i '' -u root -p 'openEuler12#$' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Fri Aug 18 12:30:55 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ SSH_SCP @:/tmp/ipvsadm_restore1.txt ./ipvsadm_restore1.txt
+ src=@:/tmp/ipvsadm_restore1.txt
+ dest=./ipvsadm_restore1.txt
+ remotepasswd='openEuler12#$'
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshscp.sh -p 'openEuler12#$' -o 22 -s @:/tmp/ipvsadm_restore1.txt -d ./ipvsadm_restore1.txt
Fri Aug 18 12:30:55 2023 - WARN  - the remote password uses the default configuration.
Fri Aug 18 12:30:55 2023 - WARN  - the connect port using the default configuration
spawn scp -P 22 -r @:/tmp/ipvsadm_restore1.txt ./ipvsadm_restore1.txt
ssh: Could not resolve hostname : Name or service not known
scp: Connection closed
+ ret=255
+ test 255 -ne 0
+ LOG_ERROR 'Failed in remote SCP operation: 255'
+ message='Failed in remote SCP operation: 255'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote SCP operation: 255'
Fri Aug 18 12:30:55 2023 - ERROR - Failed in remote SCP operation: 255
+ return 255
++ grep -cE Route ./ipvsadm_restore1.txt
grep: ./ipvsadm_restore1.txt: No such file or directory
+ CHECK_RESULT '' 1
+ actual_result=
+ expect_result=1
+ mode=0
+ error_log=
+ '[' -z '' ']'
+ LOG_ERROR 'Missing actual error code.'
+ message='Missing actual error code.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Missing actual error code.'
Fri Aug 18 12:30:55 2023 - ERROR - Missing actual error code.
+ return 1
++ grep -cE rr ./ipvsadm_restore1.txt
grep: ./ipvsadm_restore1.txt: No such file or directory
+ CHECK_RESULT '' 1
+ actual_result=
+ expect_result=1
+ mode=0
+ error_log=
+ '[' -z '' ']'
+ LOG_ERROR 'Missing actual error code.'
+ message='Missing actual error code.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Missing actual error code.'
Fri Aug 18 12:30:55 2023 - ERROR - Missing actual error code.
+ return 1
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Aug 18 12:30:55 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 1
+ test 1 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Aug 18 12:30:55 2023 - ERROR - failed to execute the case.
+ exit 1
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Aug 18 12:30:55 2023 - INFO  - Start to restore the test environment.
+ SSH_CMD 'bash -x /tmp/SAVE_RESROER.sh stop'
+ cmd='bash -x /tmp/SAVE_RESROER.sh stop'
+ remoteip=
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'bash -x /tmp/SAVE_RESROER.sh stop' -i '' -u root -p 'openEuler12#$' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Fri Aug 18 12:30:56 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ rm -rf './ipvsadm_*'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Aug 18 12:30:56 2023 - INFO  - End to restore the test environment.
