+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Fri Aug 25 05:49:39 2023 - INFO  - Start to prepare the database config.
+ DNF_INSTALL libreswan
+ pkgs=libreswan
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs libreswan --node 1 --tempfile ''
+ tmpfile2='Last metadata expiration check: 2:04:58 ago on Fri 25 Aug 2023 03:44:42 AM UTC.
Dependencies resolved.
================================================================================
 Package                Architecture   Version                 Repository  Size
================================================================================
Installing:
 libreswan              x86_64         4.11-1.oe2309           OS         1.0 M
Installing dependencies:
 ldns                   x86_64         1.8.3-1.oe2309          OS         162 k
 libreswan-help         x86_64         4.11-1.oe2309           OS         275 k
 nspr                   x86_64         4.35.0-2.oe2309         OS         121 k
 nss                    x86_64         3.89.0-1.oe2309         OS         650 k
 nss-softokn            x86_64         3.89.0-1.oe2309         OS         685 k
 nss-util               x86_64         3.89.0-1.oe2309         OS         464 k

Transaction Summary
================================================================================
Install  7 Packages

Total download size: 3.3 M
Installed size: 13 M
Downloading Packages:
[MIRROR] ldns-1.8.3-1.oe2309.x86_64.rpm: Curl error (7): Couldn'\''t connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/ldns-1.8.3-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn'\''t connect to server]
[MIRROR] libreswan-4.11-1.oe2309.x86_64.rpm: Curl error (7): Couldn'\''t connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/libreswan-4.11-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn'\''t connect to server]
[MIRROR] libreswan-help-4.11-1.oe2309.x86_64.rpm: Curl error (7): Couldn'\''t connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/libreswan-help-4.11-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn'\''t connect to server]
[MIRROR] ldns-1.8.3-1.oe2309.x86_64.rpm: Curl error (7): Couldn'\''t connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/ldns-1.8.3-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn'\''t connect to server]
[MIRROR] libreswan-4.11-1.oe2309.x86_64.rpm: Curl error (7): Couldn'\''t connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/libreswan-4.11-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn'\''t connect to server]
[MIRROR] libreswan-help-4.11-1.oe2309.x86_64.rpm: Curl error (7): Couldn'\''t connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/libreswan-help-4.11-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn'\''t connect to server]
[FAILED] ldns-1.8.3-1.oe2309.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing '\''dnf clean packages'\''.
Error: Error downloading packages:
  ldns-1.8.3-1.oe2309.x86_64: Cannot download, all mirrors were already tried without success'
+ '[' -z '' ']'
+ tmpfile='Last metadata expiration check: 2:04:58 ago on Fri 25 Aug 2023 03:44:42 AM UTC.
Dependencies resolved.
================================================================================
 Package                Architecture   Version                 Repository  Size
================================================================================
Installing:
 libreswan              x86_64         4.11-1.oe2309           OS         1.0 M
Installing dependencies:
 ldns                   x86_64         1.8.3-1.oe2309          OS         162 k
 libreswan-help         x86_64         4.11-1.oe2309           OS         275 k
 nspr                   x86_64         4.35.0-2.oe2309         OS         121 k
 nss                    x86_64         3.89.0-1.oe2309         OS         650 k
 nss-softokn            x86_64         3.89.0-1.oe2309         OS         685 k
 nss-util               x86_64         3.89.0-1.oe2309         OS         464 k

Transaction Summary
================================================================================
Install  7 Packages

Total download size: 3.3 M
Installed size: 13 M
Downloading Packages:
[MIRROR] ldns-1.8.3-1.oe2309.x86_64.rpm: Curl error (7): Couldn'\''t connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/ldns-1.8.3-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn'\''t connect to server]
[MIRROR] libreswan-4.11-1.oe2309.x86_64.rpm: Curl error (7): Couldn'\''t connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/libreswan-4.11-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn'\''t connect to server]
[MIRROR] libreswan-help-4.11-1.oe2309.x86_64.rpm: Curl error (7): Couldn'\''t connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/libreswan-help-4.11-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn'\''t connect to server]
[MIRROR] ldns-1.8.3-1.oe2309.x86_64.rpm: Curl error (7): Couldn'\''t connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/ldns-1.8.3-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn'\''t connect to server]
[MIRROR] libreswan-4.11-1.oe2309.x86_64.rpm: Curl error (7): Couldn'\''t connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/libreswan-4.11-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn'\''t connect to server]
[MIRROR] libreswan-help-4.11-1.oe2309.x86_64.rpm: Curl error (7): Couldn'\''t connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/libreswan-help-4.11-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn'\''t connect to server]
[FAILED] ldns-1.8.3-1.oe2309.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing '\''dnf clean packages'\''.
Error: Error downloading packages:
  ldns-1.8.3-1.oe2309.x86_64: Cannot download, all mirrors were already tried without success'
+ ipsec restart
oe_test_libreswan_ipsec_pluto.sh: line 25: ipsec: command not found
+ touch testfile
+ test -f /run/pluto/pluto.pid
+ LOG_INFO 'End to prepare the database config.'
+ message='End to prepare the database config.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to prepare the database config.'
Fri Aug 25 05:49:40 2023 - INFO  - End to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Aug 25 05:49:40 2023 - INFO  - Start to run test.
+ ipsec pluto --dnssec-rootkey-file testfile
oe_test_libreswan_ipsec_pluto.sh: line 36: ipsec: command not found
+ CHECK_RESULT 127 0 0 'Check ipsec pluto --dnssec-rootkey-file failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check ipsec pluto --dnssec-rootkey-file failed.'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check ipsec pluto --dnssec-rootkey-file failed.'
+ LOG_ERROR 'Check ipsec pluto --dnssec-rootkey-file failed.'
+ message='Check ipsec pluto --dnssec-rootkey-file failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ipsec pluto --dnssec-rootkey-file failed.'
Fri Aug 25 05:49:40 2023 - ERROR - Check ipsec pluto --dnssec-rootkey-file failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libreswan_ipsec_pluto.sh line 37'
+ message='oe_test_libreswan_ipsec_pluto.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_libreswan_ipsec_pluto.sh line 37'
Fri Aug 25 05:49:40 2023 - ERROR - oe_test_libreswan_ipsec_pluto.sh line 37
+ return 0
+ ipsec pluto --dnssec-trusted testfile
oe_test_libreswan_ipsec_pluto.sh: line 38: ipsec: command not found
+ CHECK_RESULT 127 0 0 'Check ipsec pluto --dnssec-trusted failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check ipsec pluto --dnssec-trusted failed.'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check ipsec pluto --dnssec-trusted failed.'
+ LOG_ERROR 'Check ipsec pluto --dnssec-trusted failed.'
+ message='Check ipsec pluto --dnssec-trusted failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ipsec pluto --dnssec-trusted failed.'
Fri Aug 25 05:49:40 2023 - ERROR - Check ipsec pluto --dnssec-trusted failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libreswan_ipsec_pluto.sh line 39'
+ message='oe_test_libreswan_ipsec_pluto.sh line 39'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_libreswan_ipsec_pluto.sh line 39'
Fri Aug 25 05:49:40 2023 - ERROR - oe_test_libreswan_ipsec_pluto.sh line 39
+ return 0
+ ipsec pluto --leak-detective
oe_test_libreswan_ipsec_pluto.sh: line 40: ipsec: command not found
+ CHECK_RESULT 127 0 0 'Check ipsec pluto --leak-detective failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check ipsec pluto --leak-detective failed.'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check ipsec pluto --leak-detective failed.'
+ LOG_ERROR 'Check ipsec pluto --leak-detective failed.'
+ message='Check ipsec pluto --leak-detective failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ipsec pluto --leak-detective failed.'
Fri Aug 25 05:49:40 2023 - ERROR - Check ipsec pluto --leak-detective failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libreswan_ipsec_pluto.sh line 41'
+ message='oe_test_libreswan_ipsec_pluto.sh line 41'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_libreswan_ipsec_pluto.sh line 41'
Fri Aug 25 05:49:40 2023 - ERROR - oe_test_libreswan_ipsec_pluto.sh line 41
+ return 0
+ ipsec pluto --version
oe_test_libreswan_ipsec_pluto.sh: line 42: ipsec: command not found
+ CHECK_RESULT 127 0 0 'Check ipsec pluto version failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check ipsec pluto version failed.'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check ipsec pluto version failed.'
+ LOG_ERROR 'Check ipsec pluto version failed.'
+ message='Check ipsec pluto version failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ipsec pluto version failed.'
Fri Aug 25 05:49:40 2023 - ERROR - Check ipsec pluto version failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libreswan_ipsec_pluto.sh line 43'
+ message='oe_test_libreswan_ipsec_pluto.sh line 43'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_libreswan_ipsec_pluto.sh line 43'
Fri Aug 25 05:49:40 2023 - ERROR - oe_test_libreswan_ipsec_pluto.sh line 43
+ return 0
+ ipsec pluto --help
oe_test_libreswan_ipsec_pluto.sh: line 44: ipsec: command not found
+ CHECK_RESULT 127 0 0 'Check ipsec pluto help failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check ipsec pluto help failed.'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check ipsec pluto help failed.'
+ LOG_ERROR 'Check ipsec pluto help failed.'
+ message='Check ipsec pluto help failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ipsec pluto help failed.'
Fri Aug 25 05:49:40 2023 - ERROR - Check ipsec pluto help failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libreswan_ipsec_pluto.sh line 45'
+ message='oe_test_libreswan_ipsec_pluto.sh line 45'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_libreswan_ipsec_pluto.sh line 45'
Fri Aug 25 05:49:40 2023 - ERROR - oe_test_libreswan_ipsec_pluto.sh line 45
+ return 0
+ ipsec pluto --debug-none
oe_test_libreswan_ipsec_pluto.sh: line 48: ipsec: command not found
+ CHECK_RESULT 127 0 0 'Check ipsec pluto --debug-none failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check ipsec pluto --debug-none failed.'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check ipsec pluto --debug-none failed.'
+ LOG_ERROR 'Check ipsec pluto --debug-none failed.'
+ message='Check ipsec pluto --debug-none failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ipsec pluto --debug-none failed.'
Fri Aug 25 05:49:40 2023 - ERROR - Check ipsec pluto --debug-none failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libreswan_ipsec_pluto.sh line 49'
+ message='oe_test_libreswan_ipsec_pluto.sh line 49'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_libreswan_ipsec_pluto.sh line 49'
Fri Aug 25 05:49:40 2023 - ERROR - oe_test_libreswan_ipsec_pluto.sh line 49
+ return 0
+ ipsec pluto --debug-all
oe_test_libreswan_ipsec_pluto.sh: line 50: ipsec: command not found
+ CHECK_RESULT 127 0 0 'Check ipsec pluto --debug-all failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check ipsec pluto --debug-all failed.'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check ipsec pluto --debug-all failed.'
+ LOG_ERROR 'Check ipsec pluto --debug-all failed.'
+ message='Check ipsec pluto --debug-all failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ipsec pluto --debug-all failed.'
Fri Aug 25 05:49:40 2023 - ERROR - Check ipsec pluto --debug-all failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libreswan_ipsec_pluto.sh line 51'
+ message='oe_test_libreswan_ipsec_pluto.sh line 51'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_libreswan_ipsec_pluto.sh line 51'
Fri Aug 25 05:49:40 2023 - ERROR - oe_test_libreswan_ipsec_pluto.sh line 51
+ return 0
+ ipsec pluto --debug all
oe_test_libreswan_ipsec_pluto.sh: line 52: ipsec: command not found
+ CHECK_RESULT 127 0 0 'Check ipsec pluto --debug failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check ipsec pluto --debug failed.'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check ipsec pluto --debug failed.'
+ LOG_ERROR 'Check ipsec pluto --debug failed.'
+ message='Check ipsec pluto --debug failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ipsec pluto --debug failed.'
Fri Aug 25 05:49:40 2023 - ERROR - Check ipsec pluto --debug failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libreswan_ipsec_pluto.sh line 53'
+ message='oe_test_libreswan_ipsec_pluto.sh line 53'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_libreswan_ipsec_pluto.sh line 53'
Fri Aug 25 05:49:40 2023 - ERROR - oe_test_libreswan_ipsec_pluto.sh line 53
+ return 0
+ ipsec pluto --listen 127.0.0.1
oe_test_libreswan_ipsec_pluto.sh: line 56: ipsec: command not found
+ CHECK_RESULT 127 0 0 'Check ipsec pluto --listen failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check ipsec pluto --listen failed.'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check ipsec pluto --listen failed.'
+ LOG_ERROR 'Check ipsec pluto --listen failed.'
+ message='Check ipsec pluto --listen failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ipsec pluto --listen failed.'
Fri Aug 25 05:49:40 2023 - ERROR - Check ipsec pluto --listen failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libreswan_ipsec_pluto.sh line 57'
+ message='oe_test_libreswan_ipsec_pluto.sh line 57'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_libreswan_ipsec_pluto.sh line 57'
Fri Aug 25 05:49:40 2023 - ERROR - oe_test_libreswan_ipsec_pluto.sh line 57
+ return 0
+ ipsec pluto --listen-tcp
oe_test_libreswan_ipsec_pluto.sh: line 58: ipsec: command not found
+ CHECK_RESULT 127 0 0 'Check ipsec pluto --listen-tcp failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check ipsec pluto --listen-tcp failed.'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check ipsec pluto --listen-tcp failed.'
+ LOG_ERROR 'Check ipsec pluto --listen-tcp failed.'
+ message='Check ipsec pluto --listen-tcp failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ipsec pluto --listen-tcp failed.'
Fri Aug 25 05:49:40 2023 - ERROR - Check ipsec pluto --listen-tcp failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libreswan_ipsec_pluto.sh line 59'
+ message='oe_test_libreswan_ipsec_pluto.sh line 59'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_libreswan_ipsec_pluto.sh line 59'
Fri Aug 25 05:49:40 2023 - ERROR - oe_test_libreswan_ipsec_pluto.sh line 59
+ return 0
+ ipsec pluto --no-listen-udp
oe_test_libreswan_ipsec_pluto.sh: line 60: ipsec: command not found
+ CHECK_RESULT 127 0 0 'Check ipsec pluto --no-listen-udp failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check ipsec pluto --no-listen-udp failed.'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check ipsec pluto --no-listen-udp failed.'
+ LOG_ERROR 'Check ipsec pluto --no-listen-udp failed.'
+ message='Check ipsec pluto --no-listen-udp failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ipsec pluto --no-listen-udp failed.'
Fri Aug 25 05:49:40 2023 - ERROR - Check ipsec pluto --no-listen-udp failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libreswan_ipsec_pluto.sh line 61'
+ message='oe_test_libreswan_ipsec_pluto.sh line 61'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_libreswan_ipsec_pluto.sh line 61'
Fri Aug 25 05:49:40 2023 - ERROR - oe_test_libreswan_ipsec_pluto.sh line 61
+ return 0
+ ipsec pluto --log-no-ip --stderrlog --logfile testlog
oe_test_libreswan_ipsec_pluto.sh: line 64: ipsec: command not found
+ CHECK_RESULT 127 0 0 'Check ipsec pluto --log-no-ip --stderrlog --logfile testlog failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check ipsec pluto --log-no-ip --stderrlog --logfile testlog failed.'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check ipsec pluto --log-no-ip --stderrlog --logfile testlog failed.'
+ LOG_ERROR 'Check ipsec pluto --log-no-ip --stderrlog --logfile testlog failed.'
+ message='Check ipsec pluto --log-no-ip --stderrlog --logfile testlog failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ipsec pluto --log-no-ip --stderrlog --logfile testlog failed.'
Fri Aug 25 05:49:40 2023 - ERROR - Check ipsec pluto --log-no-ip --stderrlog --logfile testlog failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libreswan_ipsec_pluto.sh line 65'
+ message='oe_test_libreswan_ipsec_pluto.sh line 65'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_libreswan_ipsec_pluto.sh line 65'
Fri Aug 25 05:49:40 2023 - ERROR - oe_test_libreswan_ipsec_pluto.sh line 65
+ return 0
+ ipsec pluto --log-no-time --stderrlog
oe_test_libreswan_ipsec_pluto.sh: line 66: ipsec: command not found
+ CHECK_RESULT 127 0 0 'Check ipsec pluto --log-no-time --stderrlog failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check ipsec pluto --log-no-time --stderrlog failed.'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check ipsec pluto --log-no-time --stderrlog failed.'
+ LOG_ERROR 'Check ipsec pluto --log-no-time --stderrlog failed.'
+ message='Check ipsec pluto --log-no-time --stderrlog failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ipsec pluto --log-no-time --stderrlog failed.'
Fri Aug 25 05:49:40 2023 - ERROR - Check ipsec pluto --log-no-time --stderrlog failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libreswan_ipsec_pluto.sh line 67'
+ message='oe_test_libreswan_ipsec_pluto.sh line 67'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_libreswan_ipsec_pluto.sh line 67'
Fri Aug 25 05:49:40 2023 - ERROR - oe_test_libreswan_ipsec_pluto.sh line 67
+ return 0
+ ipsec pluto --log-no-append --stderrlog
oe_test_libreswan_ipsec_pluto.sh: line 68: ipsec: command not found
+ CHECK_RESULT 127 0 0 'Check ipsec pluto --log-no-append --stderrlog failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check ipsec pluto --log-no-append --stderrlog failed.'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check ipsec pluto --log-no-append --stderrlog failed.'
+ LOG_ERROR 'Check ipsec pluto --log-no-append --stderrlog failed.'
+ message='Check ipsec pluto --log-no-append --stderrlog failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ipsec pluto --log-no-append --stderrlog failed.'
Fri Aug 25 05:49:40 2023 - ERROR - Check ipsec pluto --log-no-append --stderrlog failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libreswan_ipsec_pluto.sh line 69'
+ message='oe_test_libreswan_ipsec_pluto.sh line 69'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_libreswan_ipsec_pluto.sh line 69'
Fri Aug 25 05:49:40 2023 - ERROR - oe_test_libreswan_ipsec_pluto.sh line 69
+ return 0
+ ipsec pluto --log-no-audit --stderrlog
oe_test_libreswan_ipsec_pluto.sh: line 70: ipsec: command not found
+ CHECK_RESULT 127 0 0 'Check ipsec pluto --log-no-audit --stderrlog failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check ipsec pluto --log-no-audit --stderrlog failed.'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check ipsec pluto --log-no-audit --stderrlog failed.'
+ LOG_ERROR 'Check ipsec pluto --log-no-audit --stderrlog failed.'
+ message='Check ipsec pluto --log-no-audit --stderrlog failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ipsec pluto --log-no-audit --stderrlog failed.'
Fri Aug 25 05:49:40 2023 - ERROR - Check ipsec pluto --log-no-audit --stderrlog failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libreswan_ipsec_pluto.sh line 71'
+ message='oe_test_libreswan_ipsec_pluto.sh line 71'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_libreswan_ipsec_pluto.sh line 71'
Fri Aug 25 05:49:40 2023 - ERROR - oe_test_libreswan_ipsec_pluto.sh line 71
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Aug 25 05:49:40 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 15
+ test 15 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Aug 25 05:49:40 2023 - ERROR - failed to execute the case.
+ exit 15
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Aug 25 05:49:40 2023 - INFO  - Start to restore the test environment.
+ test -f /run/pluto/pluto.pid
+ rm -f /run/pluto/pluto.pid testfile testlog
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z Last metadata expiration check: 2:04:58 ago on Fri 25 Aug 2023 03:44:42 AM UTC.
Dependencies resolved.
================================================================================
 Package                Architecture   Version                 Repository  Size
================================================================================
Installing:
 libreswan              x86_64         4.11-1.oe2309           OS         1.0 M
Installing dependencies:
 ldns                   x86_64         1.8.3-1.oe2309          OS         162 k
 libreswan-help         x86_64         4.11-1.oe2309           OS         275 k
 nspr                   x86_64         4.35.0-2.oe2309         OS         121 k
 nss                    x86_64         3.89.0-1.oe2309         OS         650 k
 nss-softokn            x86_64         3.89.0-1.oe2309         OS         685 k
 nss-util               x86_64         3.89.0-1.oe2309         OS         464 k

Transaction Summary
================================================================================
Install  7 Packages

Total download size: 3.3 M
Installed size: 13 M
Downloading Packages:
[MIRROR] ldns-1.8.3-1.oe2309.x86_64.rpm: Curl error (7): Couldn't connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/ldns-1.8.3-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn't connect to server]
[MIRROR] libreswan-4.11-1.oe2309.x86_64.rpm: Curl error (7): Couldn't connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/libreswan-4.11-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn't connect to server]
[MIRROR] libreswan-help-4.11-1.oe2309.x86_64.rpm: Curl error (7): Couldn't connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/libreswan-help-4.11-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn't connect to server]
[MIRROR] ldns-1.8.3-1.oe2309.x86_64.rpm: Curl error (7): Couldn't connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/ldns-1.8.3-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn't connect to server]
[MIRROR] libreswan-4.11-1.oe2309.x86_64.rpm: Curl error (7): Couldn't connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/libreswan-4.11-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn't connect to server]
[MIRROR] libreswan-help-4.11-1.oe2309.x86_64.rpm: Curl error (7): Couldn't connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/libreswan-help-4.11-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn't connect to server]
[FAILED] ldns-1.8.3-1.oe2309.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  ldns-1.8.3-1.oe2309.x86_64: Cannot download, all mirrors were already tried without success ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile 'Last metadata expiration check: 2:04:58 ago on Fri 25 Aug 2023 03:44:42 AM UTC.
Dependencies resolved.
================================================================================
 Package                Architecture   Version                 Repository  Size
================================================================================
Installing:
 libreswan              x86_64         4.11-1.oe2309           OS         1.0 M
Installing dependencies:
 ldns                   x86_64         1.8.3-1.oe2309          OS         162 k
 libreswan-help         x86_64         4.11-1.oe2309           OS         275 k
 nspr                   x86_64         4.35.0-2.oe2309         OS         121 k
 nss                    x86_64         3.89.0-1.oe2309         OS         650 k
 nss-softokn            x86_64         3.89.0-1.oe2309         OS         685 k
 nss-util               x86_64         3.89.0-1.oe2309         OS         464 k

Transaction Summary
================================================================================
Install  7 Packages

Total download size: 3.3 M
Installed size: 13 M
Downloading Packages:
[MIRROR] ldns-1.8.3-1.oe2309.x86_64.rpm: Curl error (7): Couldn'\''t connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/ldns-1.8.3-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn'\''t connect to server]
[MIRROR] libreswan-4.11-1.oe2309.x86_64.rpm: Curl error (7): Couldn'\''t connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/libreswan-4.11-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn'\''t connect to server]
[MIRROR] libreswan-help-4.11-1.oe2309.x86_64.rpm: Curl error (7): Couldn'\''t connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/libreswan-help-4.11-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn'\''t connect to server]
[MIRROR] ldns-1.8.3-1.oe2309.x86_64.rpm: Curl error (7): Couldn'\''t connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/ldns-1.8.3-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn'\''t connect to server]
[MIRROR] libreswan-4.11-1.oe2309.x86_64.rpm: Curl error (7): Couldn'\''t connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/libreswan-4.11-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn'\''t connect to server]
[MIRROR] libreswan-help-4.11-1.oe2309.x86_64.rpm: Curl error (7): Couldn'\''t connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/libreswan-help-4.11-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn'\''t connect to server]
[FAILED] ldns-1.8.3-1.oe2309.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing '\''dnf clean packages'\''.
Error: Error downloading packages:
  ldns-1.8.3-1.oe2309.x86_64: Cannot download, all mirrors were already tried without success'
Traceback (most recent call last):
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 181, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 152, in rpm_remove
    with open(tmpfile, "r") as f:
         ^^^^^^^^^^^^^^^^^^
OSError: [Errno 36] File name too long: "Last metadata expiration check: 2:04:58 ago on Fri 25 Aug 2023 03:44:42 AM UTC.\nDependencies resolved.\n================================================================================\n Package                Architecture   Version                 Repository  Size\n================================================================================\nInstalling:\n libreswan              x86_64         4.11-1.oe2309           OS         1.0 M\nInstalling dependencies:\n ldns                   x86_64         1.8.3-1.oe2309          OS         162 k\n libreswan-help         x86_64         4.11-1.oe2309           OS         275 k\n nspr                   x86_64         4.35.0-2.oe2309         OS         121 k\n nss                    x86_64         3.89.0-1.oe2309         OS         650 k\n nss-softokn            x86_64         3.89.0-1.oe2309         OS         685 k\n nss-util               x86_64         3.89.0-1.oe2309         OS         464 k\n\nTransaction Summary\n================================================================================\nInstall  7 Packages\n\nTotal download size: 3.3 M\nInstalled size: 13 M\nDownloading Packages:\n[MIRROR] ldns-1.8.3-1.oe2309.x86_64.rpm: Curl error (7): Couldn't connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/ldns-1.8.3-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn't connect to server]\n[MIRROR] libreswan-4.11-1.oe2309.x86_64.rpm: Curl error (7): Couldn't connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/libreswan-4.11-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn't connect to server]\n[MIRROR] libreswan-help-4.11-1.oe2309.x86_64.rpm: Curl error (7): Couldn't connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/libreswan-help-4.11-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn't connect to server]\n[MIRROR] ldns-1.8.3-1.oe2309.x86_64.rpm: Curl error (7): Couldn't connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/ldns-1.8.3-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn't connect to server]\n[MIRROR] libreswan-4.11-1.oe2309.x86_64.rpm: Curl error (7): Couldn't connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/libreswan-4.11-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn't connect to server]\n[MIRROR] libreswan-help-4.11-1.oe2309.x86_64.rpm: Curl error (7): Couldn't connect to server for http://121.36.84.172/dailybuild/openEuler-23.09/alpha_openeuler-2023-08-14-14-17-53/OS/x86_64/Packages/libreswan-help-4.11-1.oe2309.x86_64.rpm [Failed to connect to 121.36.84.172 port 80 after 0 ms: Couldn't connect to server]\n[FAILED] ldns-1.8.3-1.oe2309.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success\n\nThe downloaded packages were saved in cache until the next successful transaction.\nYou can remove cached packages by executing 'dnf clean packages'.\nError: Error downloading packages:\n  ldns-1.8.3-1.oe2309.x86_64: Cannot download, all mirrors were already tried without success"
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Aug 25 05:49:40 2023 - INFO  - End to restore the test environment.
