+ source ../common/common_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Fri Aug 25 05:21:36 2023 - INFO  - Start environmental preparation.
+ cp /etc/dhcp/dhcpd6.conf /etc/dhcp/dhcpd6.bak
+ echo 'default-lease-time 2592000;
preferred-lifetime 604800;
option dhcp-renewal-time 3600;
option dhcp-rebinding-time 7200;
allow leasequery;
option dhcp6.info-refresh-time 21600;
subnet6 2001:db8::0/64 {
    range6 2001:db8::50 2001:db8::100;
}'
+ ip addr add 2001:db8::1 dev ''
Cannot find device ""
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Fri Aug 25 05:21:36 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Fri Aug 25 05:21:36 2023 - INFO  - Start testing...
+ test_execution dhcpd6.service
+ service=dhcpd6.service
++ date '+%Y-%m-%d %T'
+ log_time='2023-08-25 05:21:36'
+ test_restart dhcpd6.service
+ service=dhcpd6.service
+ systemctl restart dhcpd6.service
Job for dhcpd6.service failed because the control process exited with error code.
See "systemctl status dhcpd6.service" and "journalctl -xeu dhcpd6.service" for details.
+ CHECK_RESULT 1 0 0 'dhcpd6.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='dhcpd6.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'dhcpd6.service restart failed'
+ LOG_ERROR 'dhcpd6.service restart failed'
+ message='dhcpd6.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'dhcpd6.service restart failed'
Fri Aug 25 05:21:36 2023 - ERROR - dhcpd6.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Fri Aug 25 05:21:36 2023 - ERROR - ../common/common_lib.sh line 34
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status dhcpd6.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'dhcpd6.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='dhcpd6.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'dhcpd6.service restart failed'
+ LOG_ERROR 'dhcpd6.service restart failed'
+ message='dhcpd6.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'dhcpd6.service restart failed'
Fri Aug 25 05:21:41 2023 - ERROR - dhcpd6.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Fri Aug 25 05:21:41 2023 - ERROR - ../common/common_lib.sh line 37
+ return 0
+ systemctl stop dhcpd6.service
+ CHECK_RESULT 0 0 0 'dhcpd6.service stop failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='dhcpd6.service stop failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status dhcpd6.service
+ grep 'Active: inactive'
+ CHECK_RESULT 1 0 0 'dhcpd6.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='dhcpd6.service stop failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'dhcpd6.service stop failed'
+ LOG_ERROR 'dhcpd6.service stop failed'
+ message='dhcpd6.service stop failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'dhcpd6.service stop failed'
Fri Aug 25 05:21:46 2023 - ERROR - dhcpd6.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Fri Aug 25 05:21:46 2023 - ERROR - ../common/common_lib.sh line 42
+ return 0
+ systemctl start dhcpd6.service
Job for dhcpd6.service failed because the control process exited with error code.
See "systemctl status dhcpd6.service" and "journalctl -xeu dhcpd6.service" for details.
+ CHECK_RESULT 1 0 0 'dhcpd6.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='dhcpd6.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'dhcpd6.service start failed'
+ LOG_ERROR 'dhcpd6.service start failed'
+ message='dhcpd6.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'dhcpd6.service start failed'
Fri Aug 25 05:21:46 2023 - ERROR - dhcpd6.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Fri Aug 25 05:21:46 2023 - ERROR - ../common/common_lib.sh line 44
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status dhcpd6.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'dhcpd6.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='dhcpd6.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'dhcpd6.service start failed'
+ LOG_ERROR 'dhcpd6.service start failed'
+ message='dhcpd6.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'dhcpd6.service start failed'
Fri Aug 25 05:21:51 2023 - ERROR - dhcpd6.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Fri Aug 25 05:21:51 2023 - ERROR - ../common/common_lib.sh line 47
+ return 0
+ test_enabled dhcpd6.service
+ service=dhcpd6.service
++ systemctl is-enabled dhcpd6.service
+ state=disabled
+ '[' disabled == enabled ']'
+ '[' disabled == disabled ']'
++ systemctl enable dhcpd6.service
++ grep 'Created symlink'
++ awk '{print $3}'
+ symlink_file=/etc/systemd/system/multi-user.target.wants/dhcpd6.service
+ find /etc/systemd/system/multi-user.target.wants/dhcpd6.service
/etc/systemd/system/multi-user.target.wants/dhcpd6.service
+ CHECK_RESULT 0 0 0 'dhcpd6.service enable failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='dhcpd6.service enable failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl disable dhcpd6.service
Removed "/etc/systemd/system/multi-user.target.wants/dhcpd6.service".
+ find /etc/systemd/system/multi-user.target.wants/dhcpd6.service
find: ‘/etc/systemd/system/multi-user.target.wants/dhcpd6.service’: No such file or directory
+ CHECK_RESULT 1 0 1 'dhcpd6.service disable failed'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='dhcpd6.service disable failed'
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ journalctl --since '2023-08-25 05:21:36' -u dhcpd6.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
Aug 25 05:21:36 10.0.2.15 systemd[1]: dhcpd6.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 05:21:36 10.0.2.15 systemd[1]: dhcpd6.service: Failed with result 'exit-code'.
Aug 25 05:21:36 10.0.2.15 systemd[1]: Failed to start DHCPv6 Server Daemon.
Aug 25 05:21:46 10.0.2.15 systemd[1]: dhcpd6.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 05:21:46 10.0.2.15 systemd[1]: dhcpd6.service: Failed with result 'exit-code'.
Aug 25 05:21:46 10.0.2.15 systemd[1]: Failed to start DHCPv6 Server Daemon.
+ CHECK_RESULT 0 0 1 'There is an error message for the log of dhcpd6.service'
+ actual_result=0
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of dhcpd6.service'
+ '[' -z 0 ']'
+ '[' 1 -eq 0 ']'
+ test 0x == 0x
+ test -n 'There is an error message for the log of dhcpd6.service'
+ LOG_ERROR 'There is an error message for the log of dhcpd6.service'
+ message='There is an error message for the log of dhcpd6.service'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'There is an error message for the log of dhcpd6.service'
Fri Aug 25 05:21:52 2023 - ERROR - There is an error message for the log of dhcpd6.service
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 28'
+ message='../common/common_lib.sh line 28'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 28'
Fri Aug 25 05:21:52 2023 - ERROR - ../common/common_lib.sh line 28
+ return 0
+ test_reload dhcpd6.service
+ service=dhcpd6.service
+ systemctl start dhcpd6.service
Job for dhcpd6.service failed because the control process exited with error code.
See "systemctl status dhcpd6.service" and "journalctl -xeu dhcpd6.service" for details.
+ systemctl reload dhcpd6.service
+ grep 'Job type reload is not applicable'
Failed to reload dhcpd6.service: Job type reload is not applicable for unit dhcpd6.service.
+ CHECK_RESULT 0 0 0 'Job type reload is not applicable for unit dhcpd6.service'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Job type reload is not applicable for unit dhcpd6.service'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl status dhcpd6.service
+ grep 'Active: active'
+ systemctl status dhcpd6.service
+ grep 'inactive (dead)'
+ return 1
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Fri Aug 25 05:21:52 2023 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 6
+ test 6 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Aug 25 05:21:52 2023 - ERROR - failed to execute the case.
+ exit 6
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Fri Aug 25 05:21:52 2023 - INFO  - start environment cleanup.
+ systemctl stop dhcpd6.service
+ mv -f /etc/dhcp/dhcpd6.bak /etc/dhcp/dhcpd6.conf
+ ip addr del 2001:db8::1 dev ''
Cannot find device ""
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Fri Aug 25 05:21:52 2023 - INFO  - Finish environment cleanup!
